my_dbt_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: intrepid-nova-477712-i7
      keyfile: /usr/app/gcp-key.json
      dataset: my_dbt_project
      threads: 4
    